name: Package and Install

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  install-dev:
    name: "Verify Dev Env"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.10", "3.9", "3.8", "3.7", "3.6", "2.7", "pypy-3.8", "pypy-3.7", "pypy2"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install in dev mode"
        run: "python -m pip install -e .[dev]"
      - name: "Import package"
        run: "python -c 'import qbittorrentapi; print(qbittorrentapi.Client())'"

  package:
    name: "Build & Verify Package"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"

      - name: "Install twine"
        run: "python -m pip install --upgrade pip setuptools wheel twine"
      - name: "Build package"
        run: "python setup.py sdist bdist_wheel"
      - name: "List result"
        run: "ls -l dist"
      - name: "Check long_description"
        run: "python -m twine check dist/*"
